version: '3.8'

services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data

  pgbouncer:
    image: pgbouncer/pgbouncer:latest
    ports:
      - '6432:6432'
    depends_on:
      - db
    environment:
      DATABASES_HOST: db
      DATABASES_PORT: 5432
      DATABASES_USER: postgres
      DATABASES_PASSWORD: postgres
    volumes:
      - ./pgbouncer:/etc/pgbouncer

  pgbouncer-dashboard:
    image: pgbouncer/pgbouncer-dashboard
    ports:
      - '8081:80'
    depends_on:
      - pgbouncer

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - '5050:80'
    depends_on:
      - pgbouncer
    volumes:
      - pgadmin:/var/lib/pgadmin

  app:
    container_name: app
    build:
      context: ./testapp
    depends_on:
      - pgbouncer
    ports:
      - 8000:8000
    environment:
      DB_HOST: pgbouncer
      DB_PORT: 6432
      DB_USER: postgres
      DB_PASSWORD: postgres
    volumes:
      - './:/src'

volumes:
  db:
    driver: local
  pgadmin:
    driver: local
  pgbouncer:
    driver: local
